name: Update latest long video

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"   # كل ساعة

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Fetch latest long video
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
          YT_CHANNEL_ID: "UCJ7ltkpYPM7xI3DgMR1vvbg"
        run: node scripts/fetch-latest-long.js

      - name: Commit and push if changed
        run: |
          git config user.name "mlo5-bot"
          git config user.email "actions@users.noreply.github.com"
          git add latest-long.json
          git diff --cached --quiet || git commit -m "Update latest long video"
          git push
